## 判斷遺失值產生原因
+ 有些資訊是暫時無法讀取。
+ 有些資訊是被遺漏。
+ 有些對象的某些屬性特徵是不存在。
+ 有些資訊被認為不重要。
+ 操作這些資訊的代價太大而被遺棄。

In [12]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
1.0,2.0,x,4
5.5,34,3.4,x
10,x,11.5,8.5
'''
data3 = pd.read_csv(StringIO(csv_data))
print(data3)
print(data3.isnull())
data3.replace("x",np.nan,inplace=True)
print(data3)
print(data3.isnull().any())
print(data3.isnull().sum())
print("========count==============")
print(print(data3.count()))
print("========mean==============")
print(data3.mean())

      A    B     C    D
0   1.0  2.0     x    4
1   5.5   34   3.4    x
2  10.0    x  11.5  8.5
       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
      A    B     C    D
0   1.0  2.0   NaN    4
1   5.5   34   3.4  NaN
2  10.0  NaN  11.5  8.5
A    False
B     True
C     True
D     True
dtype: bool
A    0
B    1
C    1
D    1
dtype: int64
========count==============
A    3
B    2
C    2
D    2
dtype: int64
None
========mean==============

TypeError: can only concatenate str (not "int") to str

In [20]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
1.0,2.0,x,4
5.5,34,3.4,x
10,x,11.5,8.5
'''
data3 = pd.read_csv(StringIO(csv_data))
data3.replace("x",np.nan,inplace=True)
print(data3)
print(data3.info())
print("="*20)
for x in data3:
    if data3[x].dtype  == "object":
        data3[x] = data3[x].astype("float64")  
print("="*20)        
print(data3.info())
print("========mean==============")
print(data3.mean())

      A    B     C    D
0   1.0  2.0   NaN    4
1   5.5   34   3.4  NaN
2  10.0  NaN  11.5  8.5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      object
 2   C       2 non-null      object
 3   D       2 non-null      object
dtypes: float64(1), object(3)
memory usage: 228.0+ bytes
None
====================
====================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(4)
memory usage: 228.0 bytes
None
========mean==============
A     5.50
B    18.00
C     7.45
D     6.25
dtype: float64

## 丟棄遺失值
+ 您可以使用 dropna 方法再搭配 axis 參數方式進行搭配。
+ 默認情況下，預設為 axis = 0，也就是會沿著 Rows 進行，當發現到任何值為 NA 就會整個 Row 刪除。
+ 若加入參數 how=‘all’ 代表整個 Row 資料都是遺失值情況下才可以刪除丟棄。
+ 加入參數 thresh=N 代表刪除包含少於 N 個觀察值的 row。

In [29]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
drop=pd.read_csv(StringIO(csv_data))
print(drop)
print("刪除row缺失")
drop1 = drop.dropna(axis = 0)
print(drop1)
print("刪除Column缺失")
drop2 = drop.dropna(axis = 1)
print(drop2)
drop3 = drop.dropna(axis = 0,how="all")
print(drop3)
drop4 = drop.dropna(axis = 1,how="all")
print(drop4)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
刪除row缺失
Empty DataFrame
Columns: [A, B, C, D, E]
Index: []
刪除Column缺失
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D
0   2.0   3.0   4.0  5.0
1   6.0  34.0   6.0  NaN
2  10.0   NaN  11.0  8.0
3   NaN   NaN   NaN  NaN
4   3.0   NaN   3.0  NaN
5   NaN   5.0   NaN  NaN

In [39]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
drop=pd.read_csv(StringIO(csv_data))
print(drop)
drop5 = drop.dropna(thresh=3)#有數值得小於3就移除
print(drop5)
drop6 = drop.dropna(subset=["C","D"]) #C或D為空白就移除
print(drop6)
drop7 = drop.dropna(thresh = 2)
print(drop7)
print(drop)
drop.dropna(thresh = 2,inplace = True)
print(drop)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
      A    B     C    D   E
0   2.0  3.0   4.0  5.0 NaN
2  10.0  NaN  11.0  8.0 NaN
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
4   3.0   NaN   3.0  NaN NaN
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
4   3.0   NaN   3.0  NaN NaN

## 填充遺失值
+ 可使用 fillna 函數進行填充
  + 輸入要填充的數值
    + 補上中位數：建議補上中位數而非平均值，這樣相對來說不會受到極端值的影響。
    + 根據原本的資料分布補上亂數。
+ 以下兩種方式可以向後或者向前進行填充
   + pad/ffill          代表向後填充
   + bfill/backfill   代表向前填充

In [46]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fill_zero = fill.fillna(0)
print(fill_zero)
print("======="*10)
fill_zero = fill.fillna(0,limit=2)
print(fill_zero)
print("======="*10)
fill2 = fill.ffill()#如果當前欄位是NaN  向上一筆同欄直到非NaN的值 寫入目前欄位
print(fill2)
print("======="*10)
fill3 = fill.bfill()
print(fill3)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  0.0
3   0.0   0.0   0.0  0.0  0.0
4   3.0   0.0   3.0  0.0  0.0
5   0.0   5.0   0.0  0.0  0.0
======================================================================
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  NaN
3   0.0   0.0   0.0  0.0  NaN
4   3.0   NaN   3.0  NaN  NaN
5   0.0   5.0   0.0  NaN  NaN
======================================================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  5.0 NaN
2  10.0  34.0  11.0  8.0 NaN
3  10.0  34.0  11.0  8.0 NaN
4   3.0  34.0   3.0  8.0 NaN
5   3.0   5.0   3.0  8.0 NaN
======================================================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  8.0 NaN
2  10.0   5.0  11.0  8.0 NaN
3   3.0   5.0   3.0  NaN NaN
4   3.0   5.0   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN

In [54]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fillmean1 = fill.mean()
print(fillmean1)
print(type(fillmean1))
print(fillmean1.loc["A"])

mean = fillmean1.loc["A"]
print(fill["A"])
print(fill["A"].fillna(mean))
print("="*20)
for x in fill:
    col_to_fill = fill[x]
    col_to_fill.fillna(fillmean1.loc[x],inplace=True)
print(fill)    
##.fillna()

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
A     5.25
B    14.00
C     6.00
D     6.50
E      NaN
dtype: float64
<class 'pandas.core.series.Series'>
5.25
0     2.0
1     6.0
2    10.0
3     NaN
4     3.0
5     NaN
Name: A, dtype: float64
0     2.00
1     6.00
2    10.00
3     5.25
4     3.00
5     5.25
Name: A, dtype: float64
====================
       A     B     C    D   E
0   2.00   3.0   4.0  5.0 NaN
1   6.00  34.0   6.0  6.5 NaN
2  10.00  14.0  11.0  8.0 NaN
3   5.25  14.0   6.0  6.5 NaN
4   3.00  14.0   3.0  6.5 NaN
5   5.25   5.0   6.0  6.5 NaN

### 檢查重複

In [62]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
2,3,5,5
5,5,5,5
5,5,5,5
13,23,5,5
'''
df2=pd.read_csv(StringIO(csv_data))
print(df2)
print("="*20)
print(df2.duplicated())
print("="*20)
print(df2.duplicated("A"))
print("="*20)
print(df2.duplicated("D"))

    A   B  C  D
0   2   3  5  5
1   5   5  5  5
2   5   5  5  5
3  13  23  5  5
====================
0    False
1    False
2     True
3    False
dtype: bool
====================
0    False
1    False
2     True
3    False
dtype: bool
====================
0    False
1     True
2     True
3     True
dtype: bool

### 丟棄重複值的資料

In [71]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
2,3,5,5
5,5,5,5
5,5,5,5
13,23,5,5
'''
df2=pd.read_csv(StringIO(csv_data))
print(df2)
print("="*20)
print(df2.drop_duplicates(keep="last"))
print("="*20)
print(df2.drop_duplicates())
print("="*20)
print(df2.drop_duplicates(keep=False))
print("="*20)
print(df2.drop_duplicates(subset=["C","D"]))
print("="*20)
print(df2.drop_duplicates(subset=["C","D"],keep="last"))
print("="*20)
print(df2.drop_duplicates(subset=["C","D"],keep=False))
print("="*20)
print(df2.drop_duplicates(subset=["A","D"],keep=False))
print(df2.drop_duplicates(subset=["A","D"],keep="last"))

    A   B  C  D
0   2   3  5  5
1   5   5  5  5
2   5   5  5  5
3  13  23  5  5
====================
    A   B  C  D
0   2   3  5  5
2   5   5  5  5
3  13  23  5  5
====================
    A   B  C  D
0   2   3  5  5
1   5   5  5  5
3  13  23  5  5
====================
    A   B  C  D
0   2   3  5  5
3  13  23  5  5
====================
   A  B  C  D
0  2  3  5  5
====================
    A   B  C  D
3  13  23  5  5
====================
Empty DataFrame
Columns: [A, B, C, D]
Index: []
====================
    A   B  C  D
0   2   3  5  5
3  13  23  5  5
    A   B  C  D
0   2   3  5  5
2   5   5  5  5
3  13  23  5  5

In [74]:
import pandas as pd
import numpy as np
company=["A","B","C"]
data1=pd.DataFrame(
{"company":[company[x] for x in np.random.randint(0,len(company),20)],
"salary":np.random.randint(5,50,20),
"age":np.random.randint(15,50,20)}    
)
print(data1)

   company  salary  age
0        C      21   17
1        C       8   21
2        C      35   17
3        A      37   26
4        C      45   48
5        C       5   25
6        B      20   27
7        C       7   28
8        C      18   39
9        C      14   43
10       C      12   30
11       C      37   16
12       C      18   24
13       C      36   49
14       C      11   28
15       A      38   39
16       B      27   37
17       A      26   36
18       A      21   29
19       C      12   41

In [76]:
group = data1.groupby("company")
#print(group)
print(list(group))

[('A',    company  salary  age
3        A      37   26
15       A      38   39
17       A      26   36
18       A      21   29), ('B',    company  salary  age
6        B      20   27
16       B      27   37), ('C',    company  salary  age
0        C      21   17
1        C       8   21
2        C      35   17
4        C      45   48
5        C       5   25
7        C       7   28
8        C      18   39
9        C      14   43
10       C      12   30
11       C      37   16
12       C      18   24
13       C      36   49
14       C      11   28
19       C      12   41)]